export const transactionData = [
  {
    id: "1",
    price: 12,
    storeName: "Starbucks",
    location: "North York, ON",
    date: "17th March, 2023",
  },
  {
    id: "2",
    price: 125.233,
    storeName: "Apple Store",
    location: "London, ON",
    date: "18th March, 2023",
  },
  {
    id: "3",
    price: 19.24,
    storeName: "Cheesecake Factory",
    location: "Toronto, ON",
    date: "19th March, 2023",
  },
  {
    id: "4",
    price: 50.75,
    storeName: "Amazon",
    location: "Seattle, WA",
    date: "20th March, 2023",
  },
  {
    id: "5",
    price: 35.99,
    storeName: "Target",
    location: "New York, NY",
    date: "21st March, 2023",
  },
  {
    id: "6",
    price: 75.5,
    storeName: "Best Buy",
    location: "Los Angeles, CA",
    date: "22nd March, 2023",
  },
  {
    id: "7",
    price: 10.25,
    storeName: "McDonald's",
    location: "Chicago, IL",
    date: "23rd March, 2023",
  },
  {
    id: "8",
    price: 29.99,
    storeName: "Walmart",
    location: "Houston, TX",
    date: "24th March, 2023",
  },
  {
    id: "9",
    price: 45.8,
    storeName: "Gap",
    location: "San Francisco, CA",
    date: "25th March, 2023",
  },
  {
    id: "10",
    price: 20.0,
    storeName: "Subway",
    location: "Miami, FL",
    date: "26th March, 2023",
  },
];
